server:
  port: 8080

spring:
  application:
    name: greennote
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/greennote?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Pacific/Auckland&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    arg-name-based-constructor-auto-mapping: true

greennote:
  security:
    jwt-secret: greennote-dev-jwt-secret-key-32bytes-min
    expire-hours: 24
  storage:
    location: ./data/files
