-- Retired. This file used to drop and recreate note tables, including gn_user.
-- Import the current schema and seed data with:
--   mysql -uroot -p --default-character-set=utf8mb4 < sql/mysql/system.sql
