-- GreenNote schema and seed data.
-- Primary keys are UUID strings generated by the application. This script supplies fixed ids for seed rows.
-- Idempotent: safe to run again. It does not drop existing tables.
-- Run from GreenNote-backend:
--   mysql -uroot -p --default-character-set=utf8mb4 < sql/mysql/system.sql

CREATE DATABASE IF NOT EXISTS greennote
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE greennote;

SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS gn_dept (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    name VARCHAR(64) NOT NULL COMMENT 'Department name',
    parent_id CHAR(36) NULL COMMENT 'Parent department id, null for a root department',
    sort_no INT NOT NULL DEFAULT 0 COMMENT 'Display order, smaller first',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS gn_admin_user (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    dept_id CHAR(36) NULL COMMENT 'Department id',
    username VARCHAR(64) NOT NULL COMMENT 'Login name',
    password VARCHAR(100) NOT NULL COMMENT 'BCrypt password',
    nickname VARCHAR(64) NOT NULL COMMENT 'Display name',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id),
    CONSTRAINT uk_admin_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS gn_role (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    name VARCHAR(64) NOT NULL COMMENT 'Role name',
    code VARCHAR(64) NOT NULL COMMENT 'Role code',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id),
    CONSTRAINT uk_role_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS gn_admin_user_role (
    admin_user_id CHAR(36) NOT NULL COMMENT 'Admin user id',
    role_id CHAR(36) NOT NULL COMMENT 'Role id',
    PRIMARY KEY (admin_user_id, role_id)
);

CREATE TABLE IF NOT EXISTS gn_menu (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    parent_id CHAR(36) NULL COMMENT 'Parent menu id, null for a root menu',
    name VARCHAR(64) NOT NULL COMMENT 'Menu label',
    path VARCHAR(128) NOT NULL COMMENT 'Frontend route',
    sort_no INT NOT NULL DEFAULT 0 COMMENT 'Display order, smaller first',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS gn_role_menu (
    role_id CHAR(36) NOT NULL COMMENT 'Role id',
    menu_id CHAR(36) NOT NULL COMMENT 'Menu id',
    PRIMARY KEY (role_id, menu_id)
);

CREATE TABLE IF NOT EXISTS gn_dict_type (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    name VARCHAR(64) NOT NULL COMMENT 'Dictionary name',
    dict_type VARCHAR(64) NOT NULL COMMENT 'Dictionary code',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id),
    CONSTRAINT uk_dict_type UNIQUE (dict_type)
);

CREATE TABLE IF NOT EXISTS gn_dict_data (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    dict_type VARCHAR(64) NOT NULL COMMENT 'Dictionary code',
    label VARCHAR(64) NOT NULL COMMENT 'Display label',
    dict_value VARCHAR(64) NOT NULL COMMENT 'Stored value',
    sort_no INT NOT NULL DEFAULT 0 COMMENT 'Display order, smaller first',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS gn_file (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    original_name VARCHAR(255) NOT NULL COMMENT 'Original file name',
    stored_name VARCHAR(255) NOT NULL COMMENT 'Stored file name',
    url VARCHAR(512) NOT NULL COMMENT 'Public file URL',
    size_bytes BIGINT NOT NULL COMMENT 'File size in bytes',
    content_type VARCHAR(128) NOT NULL COMMENT 'MIME type',
    uploader_kind VARCHAR(16) NOT NULL COMMENT 'admin or member',
    uploader_id CHAR(36) NOT NULL COMMENT 'Uploader user id',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS gn_config (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    config_key VARCHAR(64) NOT NULL COMMENT 'Config key',
    config_value VARCHAR(1000) NOT NULL COMMENT 'Config value',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id),
    CONSTRAINT uk_config_key UNIQUE (config_key)
);

CREATE TABLE IF NOT EXISTS gn_operate_log (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    operator_id CHAR(36) NULL COMMENT 'Operator user id',
    operator_name VARCHAR(64) NOT NULL COMMENT 'Operator name',
    action VARCHAR(64) NOT NULL COMMENT 'Action code',
    detail VARCHAR(500) NOT NULL COMMENT 'Action detail',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS gn_user (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    username VARCHAR(64) NOT NULL COMMENT 'Login name',
    password VARCHAR(100) NOT NULL COMMENT 'BCrypt password',
    nickname VARCHAR(64) NOT NULL COMMENT 'Display name',
    avatar VARCHAR(512) NULL COMMENT 'Avatar URL',
    bio VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Profile bio',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id),
    CONSTRAINT uk_user_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS gn_channel (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    name VARCHAR(32) NOT NULL COMMENT 'Channel name',
    sort_no INT NOT NULL DEFAULT 0 COMMENT 'Display order, smaller first',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id),
    CONSTRAINT uk_channel_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS gn_topic (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    name VARCHAR(64) NOT NULL COMMENT 'Topic name',
    intro VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Short introduction',
    sort_no INT NOT NULL DEFAULT 0 COMMENT 'Display order, smaller first',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 enabled, 1 disabled',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    PRIMARY KEY (id),
    CONSTRAINT uk_topic_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS gn_note (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    user_id CHAR(36) NOT NULL COMMENT 'Author member id',
    channel_id CHAR(36) NULL COMMENT 'Channel id',
    type TINYINT NOT NULL COMMENT '1 image, 2 video',
    title VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Note title',
    content LONGTEXT NULL COMMENT 'Note body',
    cover_url VARCHAR(512) NULL COMMENT 'Cover image URL',
    media_json VARCHAR(4000) NULL COMMENT 'JSON array of image URLs',
    video_url VARCHAR(512) NULL COMMENT 'Video URL',
    place_name VARCHAR(128) NULL COMMENT 'Place name',
    city_name VARCHAR(64) NULL COMMENT 'City name',
    longitude DECIMAL(10, 6) NULL COMMENT 'Longitude',
    latitude DECIMAL(10, 6) NULL COMMENT 'Latitude',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '0 draft, 1 pending, 2 published, 3 offline',
    reject_reason VARCHAR(255) NULL COMMENT 'Reject or offline reason',
    like_count INT NOT NULL DEFAULT 0 COMMENT 'Like count',
    collect_count INT NOT NULL DEFAULT 0 COMMENT 'Collect count',
    comment_count INT NOT NULL DEFAULT 0 COMMENT 'Comment count',
    published_at TIMESTAMP NULL COMMENT 'Published time',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 kept, 1 deleted',
    PRIMARY KEY (id),
    INDEX idx_note_user (user_id, deleted, created_at),
    INDEX idx_note_feed (status, deleted, channel_id, published_at)
);

CREATE TABLE IF NOT EXISTS gn_note_topic (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    note_id CHAR(36) NOT NULL COMMENT 'Note id',
    topic_id CHAR(36) NOT NULL COMMENT 'Topic id',
    PRIMARY KEY (id),
    CONSTRAINT uk_note_topic UNIQUE (note_id, topic_id)
);

CREATE TABLE IF NOT EXISTS gn_note_like (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    user_id CHAR(36) NOT NULL COMMENT 'Member id',
    note_id CHAR(36) NOT NULL COMMENT 'Note id',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    PRIMARY KEY (id),
    CONSTRAINT uk_note_like UNIQUE (user_id, note_id)
);

CREATE TABLE IF NOT EXISTS gn_note_collect (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    user_id CHAR(36) NOT NULL COMMENT 'Member id',
    note_id CHAR(36) NOT NULL COMMENT 'Note id',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    PRIMARY KEY (id),
    CONSTRAINT uk_note_collect UNIQUE (user_id, note_id)
);

CREATE TABLE IF NOT EXISTS gn_note_comment (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    note_id CHAR(36) NOT NULL COMMENT 'Note id',
    user_id CHAR(36) NOT NULL COMMENT 'Author member id',
    parent_id CHAR(36) NULL COMMENT 'Parent comment id, null for a top-level comment',
    reply_to_user_id CHAR(36) NULL COMMENT 'Member id being replied to',
    content VARCHAR(1000) NOT NULL COMMENT 'Comment text',
    like_count INT NOT NULL DEFAULT 0 COMMENT 'Like count',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Updated time',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '0 kept, 1 deleted',
    PRIMARY KEY (id),
    INDEX idx_comment_note (note_id, parent_id, id)
);

CREATE TABLE IF NOT EXISTS gn_note_comment_like (
    id CHAR(36) NOT NULL COMMENT 'Primary key',
    user_id CHAR(36) NOT NULL COMMENT 'Member id',
    comment_id CHAR(36) NOT NULL COMMENT 'Comment id',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
    PRIMARY KEY (id),
    CONSTRAINT uk_comment_like UNIQUE (user_id, comment_id)
);

INSERT INTO gn_dept (id, name, parent_id, sort_no, status)
SELECT 'a1000000-0000-4000-8000-000000000001', 'Headquarters', NULL, 0, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_dept WHERE name = 'Headquarters');

INSERT INTO gn_role (id, name, code, status)
SELECT 'a2000000-0000-4000-8000-000000000001', 'Super Admin', 'super_admin', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_role WHERE code = 'super_admin');

INSERT INTO gn_admin_user (id, dept_id, username, password, nickname, status)
SELECT 'a4000000-0000-4000-8000-000000000001', d.id, 'admin', '$2a$10$jXEjVvEB0bHOwysSYhIK9unVOItbPrvEhQilA5oapdd/2Ewz4yJHG', 'Administrator', 0
FROM gn_dept d
WHERE d.name = 'Headquarters'
  AND NOT EXISTS (SELECT 1 FROM gn_admin_user WHERE username = 'admin');

INSERT INTO gn_admin_user_role (admin_user_id, role_id)
SELECT u.id, r.id
FROM gn_admin_user u
JOIN gn_role r ON r.code = 'super_admin'
WHERE u.username = 'admin'
  AND NOT EXISTS (
      SELECT 1 FROM gn_admin_user_role ur WHERE ur.admin_user_id = u.id AND ur.role_id = r.id
  );

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000001', NULL, 'Home', '/', 1, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000002', NULL, 'Members', '/members', 2, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/members');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000003', NULL, 'Site', '/site', 3, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/site');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000004', NULL, 'Departments', '/departments', 4, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/departments');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000005', NULL, 'Dictionaries', '/dictionaries', 5, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/dictionaries');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000006', NULL, 'Files', '/files', 6, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/files');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000007', NULL, 'Operation logs', '/logs', 7, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/logs');

INSERT INTO gn_role_menu (role_id, menu_id)
SELECT r.id, m.id
FROM gn_role r
JOIN gn_menu m ON 1 = 1
WHERE r.code = 'super_admin'
  AND NOT EXISTS (
      SELECT 1 FROM gn_role_menu rm WHERE rm.role_id = r.id AND rm.menu_id = m.id
  );

INSERT INTO gn_dict_type (id, name, dict_type, status)
SELECT 'a7000000-0000-4000-8000-000000000001', 'User status', 'user_status', 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_dict_type WHERE dict_type = 'user_status');

INSERT INTO gn_dict_data (id, dict_type, label, dict_value, sort_no, status)
SELECT 'a8000000-0000-4000-8000-000000000001', 'user_status', 'Active', '0', 1, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_dict_data WHERE dict_type = 'user_status' AND dict_value = '0');

INSERT INTO gn_dict_data (id, dict_type, label, dict_value, sort_no, status)
SELECT 'a8000000-0000-4000-8000-000000000002', 'user_status', 'Disabled', '1', 2, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_dict_data WHERE dict_type = 'user_status' AND dict_value = '1');

INSERT INTO gn_config (id, config_key, config_value)
SELECT 'a9000000-0000-4000-8000-000000000001', 'site.name', 'GreenNote' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_config WHERE config_key = 'site.name');

INSERT INTO gn_config (id, config_key, config_value)
SELECT 'a9000000-0000-4000-8000-000000000002', 'site.logo', '' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_config WHERE config_key = 'site.logo');

INSERT INTO gn_config (id, config_key, config_value)
SELECT 'a9000000-0000-4000-8000-000000000003', 'site.theme', '#1b6b45' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_config WHERE config_key = 'site.theme');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000008', NULL, 'Channels', '/channels', 8, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/channels');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-000000000009', NULL, 'Topics', '/topics', 9, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/topics');

INSERT INTO gn_menu (id, parent_id, name, path, sort_no, status)
SELECT 'a3000000-0000-4000-8000-00000000000a', NULL, 'Notes', '/notes', 10, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_menu WHERE path = '/notes');

INSERT INTO gn_role_menu (role_id, menu_id)
SELECT r.id, m.id
FROM gn_role r
JOIN gn_menu m ON m.path IN ('/channels', '/topics', '/notes')
WHERE r.code = 'super_admin'
  AND NOT EXISTS (
      SELECT 1 FROM gn_role_menu rm WHERE rm.role_id = r.id AND rm.menu_id = m.id
  );

INSERT INTO gn_channel (id, name, sort_no, status)
SELECT 'a5000000-0000-4000-8000-000000000001', 'Fashion', 1, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_channel WHERE name = 'Fashion');
INSERT INTO gn_channel (id, name, sort_no, status)
SELECT 'a5000000-0000-4000-8000-000000000002', 'Food', 2, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_channel WHERE name = 'Food');
INSERT INTO gn_channel (id, name, sort_no, status)
SELECT 'a5000000-0000-4000-8000-000000000003', 'Travel', 3, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_channel WHERE name = 'Travel');
INSERT INTO gn_channel (id, name, sort_no, status)
SELECT 'a5000000-0000-4000-8000-000000000004', 'Beauty', 4, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_channel WHERE name = 'Beauty');
INSERT INTO gn_channel (id, name, sort_no, status)
SELECT 'a5000000-0000-4000-8000-000000000005', 'Home', 5, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_channel WHERE name = 'Home');
INSERT INTO gn_channel (id, name, sort_no, status)
SELECT 'a5000000-0000-4000-8000-000000000006', 'Fitness', 6, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_channel WHERE name = 'Fitness');

INSERT INTO gn_topic (id, name, intro, sort_no, status)
SELECT 'a6000000-0000-4000-8000-000000000001', 'Outfit of the Day', 'One outfit a day', 1, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_topic WHERE name = 'Outfit of the Day');
INSERT INTO gn_topic (id, name, intro, sort_no, status)
SELECT 'a6000000-0000-4000-8000-000000000002', 'Home Cooking', 'Dishes you can cook at home', 2, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_topic WHERE name = 'Home Cooking');
INSERT INTO gn_topic (id, name, intro, sort_no, status)
SELECT 'a6000000-0000-4000-8000-000000000003', 'Weekend Trip', 'Short getaways', 3, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_topic WHERE name = 'Weekend Trip');
INSERT INTO gn_topic (id, name, intro, sort_no, status)
SELECT 'a6000000-0000-4000-8000-000000000004', 'Budget Finds', 'Good and affordable', 4, 0 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM gn_topic WHERE name = 'Budget Finds');
